CC = gcc -Wall -Wextra -Werror
NAME = do-op
SRC_FILES = do-op.c operations.c ft_atoi.c ft_putnbr.c ft_putstr.c

all : $(NAME)

$(NAME) :
	@$(CC) $(SRC_FILES) -o $(NAME)

clean :
 
fclean : clean
	@rm -f $(NAME)

re : fclean all